version: '3.1'
services:
  cafienne:
    image: cafienne/engine:latest
    labels:
      component: cafienne-engine
    network_mode: host
    expose:
      - 2027
    hostname: cafienne
    container_name: cafienne
    restart: on-failure
    environment:
      EVENT_DB_PROFILE: ${EVENT_DB_PROFILE:-slick.jdbc.SQLServerProfile$$}
      EVENT_DB_DRIVER: ${EVENT_DB_DRIVER:-com.microsoft.sqlserver.jdbc.SQLServerDriver}
      EVENT_DB_USER: ${EVENT_DB_USER:-SA}
      EVENT_DB_PASSWORD: ${EVENT_DB_PASSWORD:-Abc_123456}
      EVENT_DB_URL: ${EVENT_DB_URL:-jdbc:sqlserver://localhost:1433;DatabaseName=cafienneEventstore;}
      QUERY_DB_PROFILE: ${QUERY_DB_PROFILE:-slick.jdbc.SQLServerProfile$$}
      QUERY_DB_DRIVER: ${QUERY_DB_DRIVER:-com.microsoft.sqlserver.jdbc.SQLServerDriver}
      QUERY_DB_USER: ${QUERY_DB_USER:-SA}
      QUERY_DB_PASSWORD: ${QUERY_DB_PASSWORD:-Abc_123456}
      QUERY_DB_URL: ${QUERY_DB_URL:-jdbc:sqlserver://localhost:1433;DatabaseName=cafienneQuery;}
    healthcheck:
      test: ["CMD", "wget", "-s", "http://localhost:2027/api-docs/swagger.json"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /home/circleci/cafienne-engine/.circleci/run/cafienne/journal:/opt/cafienne/journal
      - /home/circleci/cafienne-engine/.circleci/target/definitions:/opt/cafienne/definitions
      - /home/circleci/cafienne-engine/.circleci/src/akka-jdbc-4-conf:/opt/cafienne/conf
      - /home/circleci/cafienne-engine/.circleci/src/bootstrap:/opt/cafienne/bootstrap
