version: '3.1'
services:

  sql-server:
    image: batav/circle-ci:sqlserver-event-data
    labels:
      component: cafienne-sql-server
    network_mode: host
    expose:
      - 1433
    ports:
      - "1433:1433"
    hostname: sql-server
    container_name: sql-server
    environment:
      SA_PASSWORD: Abc_123456
      ACCEPT_EULA: Y
      QUERY_DB: cafienneQuery
      EVENT_DB: cafienneEventstore

  cafienne-event-db:
    image: batav/circle-ci:postgres-event-data
    networks:
      - dev
    expose:
      - 5432
    ports:
      - "5431:5432"
    hostname: cafienne-event-db
    container_name: cafienne-event-db
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: mysecret
      POSTGRES_DB: cafienne-eventstore
      PGDATA: event-data

  cafienne-query-db:
    image: postgres:12.1-alpine
    networks:
      - dev
    expose:
      - 5432
    ports:
      - "5430:5432"
    hostname: cafienne-query-db
    container_name: cafienne-query-db
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: mysecret
      POSTGRES_DB: cafienne-query

  cafienne-test-token-service:
    image: spectare/oidc-token-test-service:latest
    labels:
      component: idp-test-service-for-cafienne
    network_mode: host
    expose:
      - 2377
    ports:
      - "2377:2377"
    hostname: cafienne-test-token-service
    container_name: cafienne-test-token-service
    environment:
      BIND: 0.0.0.0
      PORT: 2377

  cafienne-sqlserver:
    image: cafienne/engine:latest
    labels:
      component: cafienne-engine
    network_mode: host
    expose:
      - 2027
    ports:
      - "2027:2027"
    hostname: cafienne-sqlserver
    container_name: cafienne
    restart: on-failure
    environment:
      EVENT_DB_PROFILE: ${EVENT_DB_PROFILE:-slick.jdbc.SQLServerProfile$}
      EVENT_DB_DRIVER: ${EVENT_DB_DRIVER:-com.microsoft.sqlserver.jdbc.SQLServerDriver}
      EVENT_DB_USER: ${EVENT_DB_USER:-SA}
      EVENT_DB_PASSWORD: ${EVENT_DB_PASSWORD:-Abc_123456}
      EVENT_DB_URL: ${EVENT_DB_URL:-jdbc:sqlserver://localhost:1433;DatabaseName=cafienneEventstore;}
      PROJECTION_DB_PROFILE: ${PROJECTION_DB_PROFILE:-slick.jdbc.SQLServerProfile$}
      PROJECTION_DB_DRIVER: ${PROJECTION_DB_DRIVER:-com.microsoft.sqlserver.jdbc.SQLServerDriver}
      PROJECTION_DB_USER: ${PROJECTION_DB_USER:-SA}
      PROJECTION_DB_PASSWORD: ${PROJECTION_DB_PASSWORD:-Abc_123456}
      PROJECTION_DB_URL: ${PROJECTION_DB_URL:-jdbc:sqlserver://localhost:1433;DatabaseName=cafienneQuery;}
    healthcheck:
      test: ["CMD", "wget", "-s", "http://localhost:2027/api-docs/swagger.json"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /home/circleci/cafienne-engine/.circleci/run/cafienne/journal:/opt/cafienne/journal
      - /home/circleci/cafienne-engine/.circleci/target/definitions:/opt/cafienne/definitions
      - /home/circleci/cafienne-engine/.circleci/src/jdbc-conf:/opt/cafienne/conf
      - /home/circleci/cafienne-engine/.circleci/src/bootstrap:/opt/cafienne/bootstrap
    depends_on:
      - sql-server
      - cafienne-test-token-service

  cafienne-postgres:
    image: cafienne/engine:latest
    labels:
      component: cafienne-engine
    network_mode: host
    expose:
      - 2027
    ports:
      - "2027:2027"
    hostname: cafienne-postgres
    container_name: cafienne
    environment:
      EVENT_DB_PROFILE: ${EVENT_DB_PROFILE:-slick.jdbc.PostgresProfile$}
      EVENT_DB_DRIVER: ${EVENT_DB_DRIVER:-org.postgresql.Driver}
      EVENT_DB_USER: ${EVENT_DB_USER:-postgresuser}
      EVENT_DB_PASSWORD: ${EVENT_DB_PASSWORD:-mysecret}
      EVENT_DB_URL: ${EVENT_DB_URL:-jdbc:postgresql://localhost:5431/cafienne-eventstore?reWriteBatchedInserts=true}
      PROJECTION_DB_PROFILE: ${PROJECTION_DB_PROFILE:-slick.jdbc.PostgresProfile$}
      PROJECTION_DB_DRIVER: ${PROJECTION_DB_DRIVER:-org.postgresql.Driver}
      PROJECTION_DB_USER: ${PROJECTION_DB_USER:-postgresuser}
      PROJECTION_DB_PASSWORD: ${PROJECTION_DB_PASSWORD:-mysecret}
      PROJECTION_DB_URL: ${PROJECTION_DB_URL:-jdbc:postgresql://localhost:5430/cafienne-query?reWriteBatchedInserts=true}
    healthcheck:
      test: ["CMD", "wget", "-s", "http://localhost:2027/api-docs/swagger.json"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /home/circleci/cafienne-engine/.circleci/run/cafienne/journal:/opt/cafienne/journal
      - /home/circleci/cafienne-engine/.circleci/target/definitions:/opt/cafienne/definitions
      - /home/circleci/cafienne-engine/.circleci/src/jdbc-conf:/opt/cafienne/conf
      - /home/circleci/cafienne-engine/.circleci/src/bootstrap:/opt/cafienne/bootstrap
    depends_on:
      - cafienne-event-db
      - cafienne-query-db
      - cafienne-test-token-service

networks:
  dev:
    driver: bridge